# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: International Insurance Group, Inc. Mexico Insurance
email: info@iigins.com
description: > # this means to ignore newlines until "baseurl:"
  International Insurance Group, Inc. is the leading provider of Mexico Auto, Home, Watercraft insurance for US and Canadian residents who visit Mexico.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.iigins.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
google_analytics: UA-3065776-9

# Build settings
markdown: kramdown

# Plugins, yay!
plugins:
  # Creates an XML sitemap.
  - jekyll-sitemap
  # Compile Coffeescript to Javascript.
  - jekyll-coffeescript
  # Compile all of the assets together.
  - jekyll-assets

assets:
  # Add a CDN for where to host static files.
  # cdn: "http://yourdomain.com"
exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
  - LICENSE
  - README.md
  - server.sh
  - aliases